### ISSUE TITLE
day 19 - failed

### ISSUE THREAD

**Issue by tankf33der** [dbertolotto/advent-of-code-2020#1]
hi, I am integrating your great code to pil21's test suite and found day 19 is failing this way.

Could you fix? Thanks in advance.

```
$ pil 19.l 
res: 124
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
4 - T
((count-res (mapcar check0 Demo2Messages)))
[19.l:104] 12 -- 'test' failed
? 
```

**Comment by dbertolotto** [comment]
Hi Mike, There are some days from the 19th were I was not able to finish
everything (or make it work). I'll work on finishing the stuff in the next
few days ;)

Regards
Davide

**Comment by dbertolotto** [comment]
Hi Mike, I have disabled part 2 of the day 19 and completed some of the other missing days. I am missing part b of 4 days, the rest should work without problems now

**Comment by tankf33der** [comment]
Thanks, I will finish integration.
